### CREATE
POST http://localhost:8080/core/debtor
Accept-Language: UZ
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHcmVlZCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWQiOiI1NTQ3MjE2My0zZmNjLTQ3NTUtOGEwOS0xMzhmYTk4MTI0N2UiLCJpYXQiOjE3NjE0NjI2OTgsImV4cCI6MTc2MTU0OTA5OH0.pxT7m3pZCP1H3rBVK_PIEEXn3rzG3xBRuuLmNhlNaTRo98zirXXrBxKTWplnnqSnJnBcbJkpD6AaNRvCC9QZCg

{
  "firstName": "Olim",
  "lastName": "Olimov",
  "patronymic": "Olimovich",
  "phone": "+998901111111",
  "address": "2025-10-10",
  "birthDate": "1980-10-10",
  "email": "asdasd@gmail.com"
}

### Get all
GET http://localhost:8080/core/debtor/all
Accept-Language: UZ
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHcmVlZCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWQiOiI1MmEwNzYwOS01Mjk5LTQ3NzEtOTc4MS1lZjVjMGYwNDhhZTQiLCJpYXQiOjE3NjE0MTQzNjEsImV4cCI6MTc2MTUwMDc2MX0.Qb6GxSFtQHpieF1n4anxCBpFWFxnlPQDqt7f9j5X5Y6TIOu0T8GF8T5xlUdGQuoUekVmPq5CgvpRpag4TKON_Q

### Get by id
GET http://localhost:8080/core/debtor/f2c924a9-f49b-4e47-bdc6-de09d7c859d3
Accept-Language: UZ
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHcmVlZCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWQiOiI1MmEwNzYwOS01Mjk5LTQ3NzEtOTc4MS1lZjVjMGYwNDhhZTQiLCJpYXQiOjE3NjE0MTQzNjEsImV4cCI6MTc2MTUwMDc2MX0.Qb6GxSFtQHpieF1n4anxCBpFWFxnlPQDqt7f9j5X5Y6TIOu0T8GF8T5xlUdGQuoUekVmPq5CgvpRpag4TKON_Q

